Keep limits fix
hms-dbmi/pagoda2 pull request #143
Opened 2023-07-24 08:28 UTC by rrydbirk

2023-07-24 18:34 UTC, evanbiederstedt requested changes
Whoah!

Nice work @rrydbirk !!

Requests:
(1) @teng-gao could you doublecheck that this works as expected?
(2) @rrydbirk Could you increase the version? I'll update on CRAN

Please add your name to the authors list if you're not there too

2023-07-25 06:11 UTC, rrydbirk commented
There you go, @evanbiederstedt. I checked functionality, the error is gone and plotting works as intended.

Please note, `devel` is somewhat behind `main`, it seems you did a lot of different things that I didn't consider :-)

2023-07-25 11:54 UTC, evanbiederstedt commented
> Please note, devel is somewhat behind main, it seems you did a lot of different things that I didn't consider :-)

https://github.com/kharchenkolab/pagoda2/compare/main...devel

Looks like I modified the walkthrough sentences a bit; nothing too scary. 

Thanks @rrydbirk! I really appreciate the help here!!!

2023-07-25 11:54 UTC, evanbiederstedt approved these changes

2023-07-25 11:54 UTC, merged